# Generated by Django 5.0.6 on 2024-07-15 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Codes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imfcode", models.CharField(max_length=20)),
                ("ipncode", models.CharField(max_length=20)),
                ("bank_transfercode", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="moneytransfer",
            name="narration",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="moneytransfer",
            name="swift_code",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("Joint", "Joint"),
                    ("Personal", "Personal"),
                    ("Business", "Business"),
                    ("Check", "Check"),
                    ("Fixed", "Fixed"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="moneytransfer",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("Received", "Received"),
                    ("Local", "Local"),
                    ("International", "International"),
                    ("Commerzeciti", "Commerzeciti"),
                    ("Atm", "Atm"),
                ],
                default="Transfer",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SecurityAnswers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ans1", models.CharField(max_length=100, null=True)),
                ("ans2", models.CharField(max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionPin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_pin", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ImfBan",
        ),
    ]
