# Generated by Django 5.0.6 on 2024-07-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_transactionpin_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountprofile",
            name="account_number",
            field=models.CharField(
                default="008967556672", max_length=12, null=True, unique=True
            ),
        ),
    ]
