# Generated by Django 5.0.6 on 2024-07-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_accountprofile_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountprofile",
            name="client_id",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="passport",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
