# Generated by Django 5.0 on 2024-07-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountprofile",
            name="client_id",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="passport",
            field=models.ImageField(upload_to=""),
        ),
    ]
