# Generated by Django 5.0 on 2024-07-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_alter_accountprofile_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="verified",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="state",
            field=models.CharField(max_length=50),
        ),
    ]
