# Generated by Django 5.1.7 on 2025-05-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_accountprofile_verified_alter_accountprofile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='account_type',
            field=models.CharField(choices=[('Joint', 'Joint'), ('Personal', 'Personal'), ('Business', 'Business'), ('Check', 'Check'), ('Fixed', 'Fixed')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='client_id',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='id_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='id_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='middle_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='occupation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='passport',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='ssn',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='street_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='moneytransfer',
            name='transaction_type',
            field=models.CharField(choices=[('Received', 'Received'), ('Local', 'Local'), ('International', 'Inter-bank'), ('Inter-bank', 'Inter-bank'), ('Atm', 'Atm')], default='Transfer', max_length=20, null=True),
        ),
    ]
