# Generated by Django 5.0.6 on 2024-07-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_profile_phone1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="referal",
            name="user",
        ),
        migrations.DeleteModel(
            name="OTP",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="Referal",
        ),
    ]
