# Generated by Django 5.0.6 on 2024-07-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_banuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="banuser",
            name="ban",
            field=models.BooleanField(default=False),
        ),
    ]
