# Generated by Django 5.0.6 on 2024-07-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_banuser_ban"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="account_number",
            field=models.CharField(default="0089673556672", max_length=12),
        ),
        migrations.AddField(
            model_name="moneytransfer",
            name="date",
            field=models.DateTimeField(null=True),
        ),
    ]
