# Generated by Django 5.0 on 2024-07-11 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_accountprofile_account_number_moneytransfer_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="pending_balance",
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="balance",
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name="moneytransfer",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
