# Generated by Django 5.0 on 2024-07-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_accountprofile_pending_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneytransfer",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("Received", "Received"),
                    ("Transfer", "Transfer"),
                    ("Atm", "Atm"),
                ],
                default="Transfer",
                max_length=20,
                null=True,
            ),
        ),
    ]
